# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/meizu/sdm845/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter m1882 m1892,$(TARGET_DEVICE)),)

endif
