# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/meizu/m1892/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/meizu/m1892

PRODUCT_COPY_FILES += \
    vendor/meizu/m1892/proprietary/vendor/etc/sensors/config/config_list.txt:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/config_list.txt \
    vendor/meizu/m1892/proprietary/vendor/etc/sensors/config/sdm845_icm206xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_icm206xx_0.json \
    vendor/meizu/m1892/proprietary/vendor/firmware/ZKL_SimHei_48.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ZKL_SimHei_48.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/cleanup_ring.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cleanup_ring.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/coin_ring.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/coin_ring.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/defalm_ring.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/defalm_ring.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/defsim_ring.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/defsim_ring.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/dw_165hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dw_165hz.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/dw_166hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dw_166hz.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/dw_167hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dw_167hz.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/dw_168hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dw_168hz.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/dw_169hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dw_169hz.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/dw_170hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dw_170hz.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/dw_171hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dw_171hz.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/dw_172hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dw_172hz.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/dw_173hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dw_173hz.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/dw_174hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dw_174hz.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/dw_175hz.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dw_175hz.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/mpacc_ring.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mpacc_ring.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/mzese.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/mzese.b00 \
    vendor/meizu/m1892/proprietary/vendor/firmware/mzese.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/mzese.b01 \
    vendor/meizu/m1892/proprietary/vendor/firmware/mzese.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/mzese.b02 \
    vendor/meizu/m1892/proprietary/vendor/firmware/mzese.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/mzese.b03 \
    vendor/meizu/m1892/proprietary/vendor/firmware/mzese.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/mzese.b04 \
    vendor/meizu/m1892/proprietary/vendor/firmware/mzese.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/mzese.b05 \
    vendor/meizu/m1892/proprietary/vendor/firmware/mzese.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/mzese.b06 \
    vendor/meizu/m1892/proprietary/vendor/firmware/mzese.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/mzese.b07 \
    vendor/meizu/m1892/proprietary/vendor/firmware/mzese.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/mzese.mdt \
    vendor/meizu/m1892/proprietary/vendor/firmware/plug_usb_ring.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/plug_usb_ring.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring00.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring00.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring01.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring02.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring03.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring03.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring04.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring05.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring05.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring06.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring06.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring07.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring07.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring08.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring08.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring09.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring09.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring10.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring10.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring11.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring11.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring12.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring12.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring13.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring13.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring14.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring14.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring15.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring15.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring16.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring16.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring17.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring17.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring18.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring18.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring19.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring19.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring20.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring21.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring22.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring22.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring23.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring23.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring24.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring24.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring25.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring25.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring26.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring26.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring27.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring27.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring28.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring28.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring29.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring29.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring30.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring30.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring31.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring31.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring32.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring32.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring33.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring33.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring34.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring34.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring35.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring35.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring36.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring36.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring37.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring37.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring38.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring38.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring39.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring39.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sim_ring40.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sim_ring40.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring01.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring02.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring03.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring03.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring04.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring05.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring05.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring06.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring06.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring07.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring07.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring08.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring08.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring09.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring09.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring10.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring10.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring11.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring11.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring12.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring12.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring13.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring13.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring14.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring14.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring15.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring15.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring16.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring16.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring17.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring17.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring18.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring18.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring19.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring19.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring20.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring21.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring22.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring22.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring23.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring23.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring24.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring24.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring25.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring25.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring26.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring26.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring27.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring27.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring28.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring28.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring29.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring29.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring30.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring30.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring31.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring31.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/sms_ring32.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sms_ring32.bin \
    vendor/meizu/m1892/proprietary/vendor/firmware/syna_tp.img:$(TARGET_COPY_OUT_VENDOR)/firmware/syna_tp.img
